name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend/
        run: yarn

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'temurin'  # Updated to a distribution that supports Java 20
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: 'success'

      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Clean Gradle
        working-directory: backend/
        run: |
          ./gradlew clean

      - name: Build with Gradle
        working-directory: backend/
        run: gradle build

      - name: Run unit tests
        working-directory: backend/
        run: gradle test
        
      - name: Build React App
        working-directory: frontend/
        run: yarn build
