name: CI/CD Pipeline

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          
      - name: Build with Maven
        run: mvn -B clean package

      - name: Run tests
        run: mvn -B test

      - name: Build Spring Boot app
        run: ./mvnw clean package
        
      - name: Build React App
        run: yarn build


      - name: Run Spring Boot tests
        run: ./mvnw test
